version: "2.4"

################################################################################

services:
  tello-hoop: # image name : PROJECT_{foo}
    container_name: tello-hoop # container name
    privileged: true
    environment:
      # Display X Server GUI.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    shm_size: '8gb' # Shared memory size.
    volumes:
      # Mount the project directory.
      - ../:/root/Tello-Fly-Through-Hoop
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: tail -f /dev/null # Command to keep the container running.